{
  "artifacts": [],
  "command": "main",
  "experiment": {
    "base_dir": "/home/gradient/nico/baselines/script",
    "dependencies": [
      "baselines==0.1.5",
      "gym==0.10.5",
      "numpy==1.14.3",
      "sacred==0.7.4",
      "tensorflow==1.8.0"
    ],
    "mainfile": "run_rllab_pois_sacred.py",
    "name": "POIS",
    "repositories": [
      {
        "commit": "77b9fc057683f38a5065975070fadc6b3fec489a",
        "dirty": true,
        "url": "https://github.com/T3p/baselines.git"
      }
    ],
    "sources": [
      [
        "run_rllab_pois_sacred.py",
        "_sources/run_rllab_pois_sacred_9bbf5152284e744109b7ca3ac93968a5.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/home/gradient/anaconda3/envs/baselines/lib/python3.5/site-packages/tensorflow/python/client/session.py\", line 282, in __init__\n    fetch, allow_tensor=True, allow_operation=True))\n",
    "  File \"/home/gradient/anaconda3/envs/baselines/lib/python3.5/site-packages/tensorflow/python/framework/ops.py\", line 3590, in as_graph_element\n    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)\n",
    "  File \"/home/gradient/anaconda3/envs/baselines/lib/python3.5/site-packages/tensorflow/python/framework/ops.py\", line 3679, in _as_graph_element_locked\n    types_str))\n",
    "TypeError: Can not convert a int into a Tensor or Operation.\n",
    "\nDuring handling of the above exception, another exception occurred:\n\n",
    "Traceback (most recent call last):\n",
    "  File \"/home/gradient/.local/lib/python3.5/site-packages/sacred/config/captured_function.py\", line 46, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"script/run_rllab_pois_sacred.py\", line 154, in main\n    max_iters=max_iters)\n",
    "  File \"script/run_rllab_pois_sacred.py\", line 129, in train\n    clipping=clipping, entropy=entropy)\n",
    "  File \"/home/gradient/nico/baselines/baselines/pois/pois.py\", line 671, in learn\n    meanlosses = np.array(compute_losses(*args))\n",
    "  File \"/home/gradient/nico/baselines/baselines/common/tf_util.py\", line 195, in __call__\n    results = tf.get_default_session().run(self.outputs_update, feed_dict=feed_dict)[:-1]\n",
    "  File \"/home/gradient/anaconda3/envs/baselines/lib/python3.5/site-packages/tensorflow/python/client/session.py\", line 900, in run\n    run_metadata_ptr)\n",
    "  File \"/home/gradient/anaconda3/envs/baselines/lib/python3.5/site-packages/tensorflow/python/client/session.py\", line 1120, in _run\n    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)\n",
    "  File \"/home/gradient/anaconda3/envs/baselines/lib/python3.5/site-packages/tensorflow/python/client/session.py\", line 427, in __init__\n    self._fetch_mapper = _FetchMapper.for_fetch(fetches)\n",
    "  File \"/home/gradient/anaconda3/envs/baselines/lib/python3.5/site-packages/tensorflow/python/client/session.py\", line 245, in for_fetch\n    return _ListFetchMapper(fetch)\n",
    "  File \"/home/gradient/anaconda3/envs/baselines/lib/python3.5/site-packages/tensorflow/python/client/session.py\", line 352, in __init__\n    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]\n",
    "  File \"/home/gradient/anaconda3/envs/baselines/lib/python3.5/site-packages/tensorflow/python/client/session.py\", line 352, in <listcomp>\n    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]\n",
    "  File \"/home/gradient/anaconda3/envs/baselines/lib/python3.5/site-packages/tensorflow/python/client/session.py\", line 253, in for_fetch\n    return _ElementFetchMapper(fetches, contraction_fn)\n",
    "  File \"/home/gradient/anaconda3/envs/baselines/lib/python3.5/site-packages/tensorflow/python/client/session.py\", line 286, in __init__\n    (fetch, type(fetch), str(e)))\n",
    "TypeError: Fetch argument 2 has invalid type <class 'int'>, must be a string or Tensor. (Can not convert a int into a Tensor or Operation.)\n"
  ],
  "heartbeat": "2018-08-30T09:32:49.784690",
  "host": {
    "ENV": {},
    "cpu": "Intel(R) Xeon(R) CPU E5-4610 v2 @ 2.30GHz",
    "hostname": "nash",
    "os": [
      "Linux",
      "Linux-4.4.0-130-generic-x86_64-with-debian-stretch-sid"
    ],
    "python_version": "3.5.5"
  },
  "meta": {
    "command": "main",
    "options": {
      "--beat_interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print_config": false,
      "--priority": null,
      "--queue": false,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [
        "env=inverted-pendulum",
        "iw_method=is",
        "bound=max-d2",
        "policy=linear",
        "logdir=ip_linear",
        "delta=0.9",
        "center=True",
        "gamma=0.99",
        "njobs=1",
        "seed=109",
        "entropy=step:10.0:2"
      ],
      "help": false,
      "with": true
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2018-08-30T09:32:38.970057",
  "status": "FAILED",
  "stop_time": "2018-08-30T09:32:49.787663"
}